---
# tasks file for awsomeweb
- name: Template index.html.j2 to index.html
  template:
    src: templates/index.html.j2
    dest: "{{ target_dir }}/index.html"
  tags:
    - nginx-templates
- name: restart nginx server
  service:
    name: nginx
    state: restarted
  tags:
  - always  

