---
- 
  hosts: db1
  tasks:
    - name: install httpd
      yum:
        name: httpd
        update_cache: yes
        state: latest
    - name: start the apache service
      service:
        name: httpd
        enabled: true
        state: started
    - name: Install firewalld latest version
      yum:
        name: firewalld
        state: latest
    - name: start and enable firewalld 
      service:
        name: firewalld
        enabled: true
        state: started
    - name: add an http rule in my firewall
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

