---
      - name: Download required tomcat
        get_url:
          url: "{{tomcat_url}}"
          dest: /usr/local
      - name: remove folder
        file:
          path: /usr/local/latest
          state: absent
      - name: extract the tomcat
        unarchive:
          src: "/usr/local/apache-tomcat-{{req_tomcat_ver}}.tar.gz"
          dest: /usr/local
          remote_src: yes
      - name: rename the tomcat home
        command: mv /usr/local/apache-tomcat-{{req_tomcat_ver}} /usr/local/latest
      - name: replace default port with required port
        template:
          src: server.xml.j2
          dest: /usr/local/latest/conf/server.xml
      - name: start tomcat
        shell: nohup /usr/local/latest/bin/startup.sh &
      - name: open port
        firewalld:
          port: 8090/tcp
          permanent: true
          immediate: yes
          state: enabled

